[master]
master_node ansible_host=3.90.110.22 private_ip=172.31.25.163

[workers]
worker_1 ansible_host=34.227.207.104 private_ip=172.31.27.224
worker_2 ansible_host=100.59.192.41 private_ip=172.31.27.246

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/tsa_cloud.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o IdentitiesOnly=yes'